CREATE TABLE participantsession(
id INT UNIQUE PRIMARY KEY AUTO_INCREMENT, 
email VARCHAR(500),
hearingStatus VARCHAR(500),
ageAcqASL INT,
age INT,
howASL VARCHAR(500),
nativeLang VARCHAR(500),
ageAcqEng INT,
langs VARCHAR(500),
interpreter VARCHAR(500),
cert VARCHAR(500),
howLongCert VARCHAR(500),
fatherNativeLang VARCHAR(500),
fatherLangs VARCHAR(500),
fatherWhenLearnEnglish INT,
motherNativeLang VARCHAR(500),
motherLangs VARCHAR(500),
motherWhenLearnEnglish INT,
gAnalyticsID VARCHAR(500),
startTime VARCHAR(500)
)
